name: Check Pull Requests
on:
  pull_request:
    branches:
        - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Copy gradle properties file
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Run unit tests
      run: ./gradlew test --stacktrace

    - name: Upload Reports
      uses: actions/upload-artifact@v1
      with:
        name: Test-Reports
        path: app/build/reports
      if: always()