name: Check Pull Requests
on:
  pull_request:
    branches:
        - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Unit tests
        run: ./gradlew test